{
 "title": "Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Host",
    "query": "SELECT DISTINCT host FROM (SELECT host FROM ping_results UNION SELECT host FROM track_results) all_hosts;"
   }
  ]
 },
 "panels": [
  {
   "title": "Latência média (Todos os hosts)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\", \n  AVG(\"rtt_avg\") AS \"Latência (ms)\"\nFROM\n  ping_results\nWHERE\n  $__timeFilter(\"timestamp\")\nGROUP BY\n  \"timestamp\"\nORDER BY\n  \"timestamp\" ASC"
    }
   ]
  },
  {
   "title": "Latência média (Host selecionado)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\", \n  AVG(\"rtt_avg\") AS \"Latência (ms)\"\nFROM\n  ping_results\nWHERE\n  \"host\" = '$Host'\n  AND $__timeFilter(\"timestamp\")\nGROUP BY\n  \"timestamp\"\nORDER BY\n  \"timestamp\" ASC"
    }
   ]
  },
  {
   "title": "Perda de pacotes média (Todos os hosts)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\", \n  AVG(\"packet_loss\") AS \"Pacotes perdidos (%)\"\nFROM\n  ping_results\nWHERE\n  $__timeFilter(\"timestamp\")\nGROUP BY\n  \"timestamp\"\nORDER BY\n  \"timestamp\" ASC"
    }
   ]
  },
  {
   "title": "Perda de pacotes média (Host selecionado)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\", \n  AVG(\"packet_loss\") AS \"Pacotes perdidos (%)\"\nFROM\n  ping_results\nWHERE\n  \"host\" = '$Host' AND $__timeFilter(\"timestamp\")\nGROUP BY\n  \"timestamp\"\nORDER BY\n  \"timestamp\" ASC"
    }
   ]
  },
  {
   "title": "Códigos de retorno (Todos os hosts)",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT status_code::TEXT,COUNT(*) AS \"Count\" FROM track_results WHERE $__timeFilter(\"timestamp\") GROUP BY status_code ORDER BY \"Count\" DESC;"
    }
   ]
  },
  {
   "title": "Códigos de retorno (Host selecionado)",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT status_code::TEXT,COUNT(*) AS \"Count\" FROM track_results WHERE \"host\" = '$Host' AND $__timeFilter(\"timestamp\") GROUP BY status_code ORDER BY \"Count\" DESC;"
    }
   ]
  },
  {
   "title": "Tempo de resposta médio (Todos os hosts)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(\"timestamp\", $__interval) AS \"time\",AVG(loading_time) AS \"Tempo (segundos)\" FROM track_results WHERE $__timeFilter(\"timestamp\") GROUP BY \"time\" ORDER BY \"time\" ASC"
    }
   ]
  },
  {
   "title": "Tempo de resposta médio (Host selecionado)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(\"timestamp\", $__interval) AS \"time\",AVG(loading_time) AS \"Tempo (segundos)\" FROM track_results WHERE \"host\" = '$Host' AND $__timeFilter(\"timestamp\") GROUP BY \"time\" ORDER BY \"time\" ASC"
    }
   ]
  },
  {
   "title": "Erros de conexão (Todos os hosts)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "WITH time_series AS (\n  SELECT \n    $__timeGroup(\"timestamp\", $__interval) AS \"time\"\n  FROM \n    track_results\n  WHERE \n    $__timeFilter(\"timestamp\")\n  GROUP BY\n    \"time\"\n)\nSELECT \n  ts.\"time\",\n  COALESCE(COUNT(tr.status_code), 0) AS \"Erros (404, 500, etc)\"\nFROM \n  time_series ts\nLEFT JOIN \n  track_results tr\n  ON $__timeFilter(tr.\"timestamp\") \n  AND $__timeGroup(tr.\"timestamp\", $__interval) = ts.\"time\"\n  AND tr.status_code >= 400\nGROUP BY \n  ts.\"time\"\nORDER BY \n  ts.\"time\" ASC\n"
    }
   ]
  },
  {
   "title": "Erros de conexão (Host selecionado)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "WITH time_series AS (\n  SELECT \n    $__timeGroup(\"timestamp\", $__interval) AS \"time\"\n  FROM \n    track_results\n  WHERE \n    \"host\" = '$Host'\n    AND $__timeFilter(\"timestamp\")\n  GROUP BY\n    \"time\"\n)\nSELECT \n  ts.\"time\",\n  COALESCE(COUNT(tr.status_code), 0) AS \"Erros (404, 500, etc)\"\nFROM \n  time_series ts\nLEFT JOIN \n  track_results tr\n  ON $__timeFilter(tr.\"timestamp\") \n  AND $__timeGroup(tr.\"timestamp\", $__interval) = ts.\"time\"\n  AND tr.status_code >= 400\nGROUP BY \n  ts.\"time\"\nORDER BY \n  ts.\"time\" ASC\n"
    }
   ]
  }
 ]
}