{
 "title": "Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Cliente",
    "query": "SELECT DISTINCT client FROM api_results ORDER BY client ASC;"
   }
  ]
 },
 "panels": [
  {
   "title": "Clientes indisponíveis",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH last_up AS (\n    SELECT \n        client,\n        MAX(timestamp) AS last_up_timestamp\n    FROM \n        api_results \n    WHERE \n        up = TRUE\n    GROUP BY \n        client\n)\nSELECT \n    t.client AS \"Cliente\",\n    MIN(t.timestamp) AS \"Horário da queda\"\nFROM \n    api_results AS t\nLEFT JOIN \n    last_up AS lu ON t.client = lu.client\nWHERE \n    t.up = FALSE\n    AND (\n        lu.last_up_timestamp IS NULL OR t.timestamp > lu.last_up_timestamp\n    )\nGROUP BY \n    t.client\nORDER BY   \n    \"Horário da queda\" ASC;"
    }
   ]
  },
  {
   "title": "Porcentagem de clientes disponíveis",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" AS \"time\", 100.0 * SUM(CASE WHEN up THEN 1 ELSE 0 END) / COUNT(*) AS \"Disponibilidade (%)\" FROM api_results WHERE $__timeFilter(\"timestamp\") GROUP BY \"timestamp\" ORDER BY \"timestamp\" ASC"
    }
   ]
  },
  {
   "title": "Consumo médio de banda (cliente selecionado)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" AS \"time\", AVG(\"bandwidth_use\")/1000000 AS \"Uso (Mbps)\" FROM api_results WHERE $__timeFilter(\"timestamp\") AND client='$Cliente' GROUP BY \"timestamp\" ORDER BY \"timestamp\" ASC"
    }
   ]
  },
  {
   "title": "Disponibilidade média (100% - <taxa de perda de pacotes>) (cliente selecionado)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" AS \"time\", AVG(\"avg_availability\") AS \"Disponibilidade (%)\" FROM api_results WHERE $__timeFilter(\"timestamp\") AND client='$Cliente' GROUP BY \"timestamp\" ORDER BY \"timestamp\" ASC"
    }
   ]
  },
  {
   "title": "Qualidade e Disponibilidade",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT \n    client,\n    timestamp AS time,\n    CASE \n        WHEN up THEN quality::text\n        ELSE 'Indisponível'\n    END AS quality_full\nFROM \n    api_results \nWHERE \n    $__timeFilter(timestamp)\nORDER BY \n    client, timestamp;\n"
    }
   ]
  }
 ]
}